name: Auto Conventional Commit with Gemini

on:
  push:
    branches-ignore: [main]  # prevent auto-commits on main
    paths-ignore:
      - '**.md'

jobs:
  rewrite-commit:
    runs-on: ubuntu-latest
    name: Rewrite commit messages using Gemini
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ensures full commit history is available

      - name: Set up Golang
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'
      - run: go version

      - name: Install GeminiCommit
        run: |
          go install github.com/tfkhdyt/geminicommit@latest

      - name: Run GeminiCommit
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          geminicommit --yes --model "gemini-2.0-flash" -c "rewrite to conventional commits"

      - name: Push rewritten commits
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git push --force
